In [2]:
import numpy
n = numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
m = numpy.asarray([[123,12,123,12,123],[],[]])

In [1]:
print(m)

NameError: name 'm' is not defined

In [5]:
import cv2


In [11]:
img  = cv2.imread("102 smallgray.png",0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
cv2.imwrite("newimage.png",img)

True

In [13]:
img[:2] #slicing image array 

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [14]:
img[:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [15]:
for i in img.flat: #accessing numpy array one by one
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [17]:
import numpy

In [19]:
# stacking numpy arrays, hstack makes horizontal stacks and vstack makes vertical stacks
ims = numpy.hstack((img,img))

In [20]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
cv2.imwrite("stackimage.png",ims) #same image is added twice(look image in folder) and it can be added thrice or more

True

In [22]:
ims1 = numpy.vstack((img,img))

In [23]:
cv2.imwrite("stackimage1.png",ims1)

True

In [25]:
ims1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
#demonstrate horizontal and vertical splitting
lst = numpy.hsplit(ims1,5) #horizontal splitting ,parameter i.e 5 is multiple of no.of columns
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [34]:
lst = numpy.vsplit(ims1,3) #vertical splitting ,parameter i.e 3 is multiple of no.of rows
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]